spring.application.name=finance-tracker-api
# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# We will use 'none' because you are manually creating the tables via SQL in Phase 2. 
# In an interview, mention that 'validate' is also great here to ensure the Java entities match the DB perfectly.
spring.jpa.hibernate.ddl-auto=none

# Show the SQL queries Hibernate generates in the terminal (great for debugging and learning)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080